# table
select * from customer_details limit 5;

# What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) from customer_details
group by gender;

# Which customers used a discount but still spent mort than the average purchase amount?
select customer_id, purchase_amount
from customer_details
where discount_applied = 'YES' and purchase_amount >= (select avg(purchase_amount) from customer_details);

#Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating), 1) review_rating
from customer_details
group by item_purchased
order by avg(review_rating) desc
limit 5;

#Compare the average Purchase Accounts between Standard and Express shipping
select shipping_type, round(avg(purchase_amount), 1) purchase_amount
from customer_details
group by shipping_type
having shipping_type in ('Express', 'Standard');

#Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount), 1) avg_purchase_amount, sum(purchase_amount) total_purchase_amount
from customer_details
group by subscription_status;

#which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(count(case when discount_applied = 'Yes' then 1 end) * 100 /count(item_purchased), 2) percent 
from customer_details
group by item_purchased
order by percent desc
limit 5;

#segment customers into new, returning and loyal based on their total no of prev purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customer_details
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

# What are the 3 most purchased products within each category?

with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_details
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

#Are customers who are repeat buyers (5 + prev purch) also likely to subscribe?

select round(count(case when subscription_status = 'Yes' then 1 end) * 100 / count(*), 2) as percent
from customer_details
where previous_purchases > 5;

#what is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as contribution
from customer_details
group by age_group
order by contribution desc;